name: EMMO check

on: [pull_request]

jobs:
  emmocheck:
    name: EMMO Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install EMMOntoPy
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install -r requirements.txt

    - name: Find and run EMMO Check on all .ttl files (excluding inferred)
      run: |
        TTL_FILES=$(find . -type f \( -path "./modules/*.ttl" -o -path "./reference/*.ttl" -o -path "./subdomains/*.ttl" -o -path "./*.ttl" \) ! -name "*inferred.ttl")
        
        if [ -z "$TTL_FILES" ]; then
          echo "No .ttl files found!"
          exit 1
        fi

        for file in $TTL_FILES; do
          echo "Running EMMO check on $file"
          emmocheck --verbose --url-from-catalog \
            --skip test_namespace \
            --skip test_quantity_dimension \
            --configfile=.github/utils/emmocheck_config.yml \
            "$file"
        done
