name: EMMO check

on: [pull_request]

jobs:
  emmocheck:
    name: EMMO Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install EMMOntoPy
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install -r requirements.txt

    - name: Run EMMO Check - battery
      run: |
        if [ -f "battery.ttl" ]; then
          emmocheck --verbose --url-from-catalog \
            --skip test_namespace \
            --skip test_quantity_dimension \
            --configfile=.github/utils/emmocheck_config.yml \
            battery.ttl
        else
          echo "battery.ttl not found!"
          exit 1
        fi

    - name: Run EMMO Check - batteryquantities
      run: |
        if [ -f "batteryquantities.ttl" ]; then
          emmocheck --verbose --url-from-catalog \
            --skip test_namespace \
            --skip test_quantity_dimension \
            --configfile=.github/utils/emmocheck_config.yml \
            batteryquantities.ttl
        elif [ -f "shared/battery-quantities.ttl" ]; then
          emmocheck --verbose --url-from-catalog \
            --skip test_namespace \
            --skip test_quantity_dimension \
            --configfile=.github/utils/emmocheck_config.yml \
            shared/battery-quantities.ttl
        else
          echo "batteryquantities.ttl or shared/battery-quantities.ttl not found!"
          exit 1
        fi
